name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:

env:
  PACKAGE_NAME: "SNetwork"
  TEST_POSTFIX: "PackageTests"
  PROFDATA_FILE: ".build/debug/codecov/default.profdata"

jobs:
  check-tools:
    name: Check Tools
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Run tool check
        run: ./scripts/check_tools.sh

  build:
    name: Build
    runs-on: macos-15
    needs: check-tools
    steps:
      - uses: actions/checkout@v4
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: .build  # Cache the entire .build folder
          key: build-${{ runner.os }}-${{ hashFiles('**/*.swift') }}  # Cache key based on source files
          restore-keys: |
            build-${{ runner.os }}-
      - name: Build
        run: ./scripts/build.sh

  test:
    name: Test
    runs-on: macos-15
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: .build
          key: build-${{ runner.os }}-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Run tests
        run: ./scripts/test.sh

  coverage:
    name: Coverage
    runs-on: macos-15
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: .build
          key: build-${{ runner.os }}-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Set test executable path
        run: ls -la & echo "TEST_EXECUTABLE=.build/debug/${{ env.PACKAGE_NAME }}${{ env.TEST_POSTFIX }}.xctest/Contents/MacOS/${{ env.PACKAGE_NAME }}${{ env.TEST_POSTFIX }}" >> $GITHUB_ENV
      - name: Run coverage
        run: ./scripts/codecov.sh

  documentation:
    name: Documentation
    runs-on: macos-15
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: .build
          key: build-${{ runner.os }}-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Generate documentation
        run: ./scripts/doc.sh
